import { z } from "zod";
export const bookGenres = {
	"Action": "action",
	"Art": "art",
	"Biography": "biography",
	"Business": "business",
	"Childrens": "childrens",
	"Classic": "classic",
	"Craft": "craft",
	"Dictionary": "dictionary",
	"Cookbook": "cookbook",
	"Encyclopedia": "encyclopedia",
	"Fantasy": "fantasy",
	"Health": "health",
	"History": "history",
	"Horror": "horror",
	"Instructional": "instructional",
	"Mystery": "mystery",
	"Photography": "photography",
	"Politics": "politics",
	"Romance": "romance",
	"Sci-Fi": "sci-fi",
	"Self-Help": "self-help",
	"Social-Sciences": "social-sciences",
	"Spirituality": "spirituality",
	"Technology": "technology",
	"Textbook": "textbook",
	"Thesaurus": "thesaurus",
	"Thriller": "thriller",
	"Travel": "travel",
	"Western": "western",
	"Comics": "comics"
} as const;
export const bookGenresToGroup = {
	"action": ["fiction"],
	"art": ["non-fiction"],
	"biography": ["non-fiction"],
	"business": ["non-fiction"],
	"childrens": ["fiction","non-fiction"],
	"classic": ["fiction"],
	"craft": ["non-fiction"],
	"dictionary": ["reference"],
	"cookbook": ["reference"],
	"encyclopedia": ["reference"],
	"fantasy": ["fiction"],
	"health": ["reference"],
	"history": ["fiction"],
	"horror": ["fiction"],
	"instructional": ["reference"],
	"mystery": ["fiction"],
	"photography": ["non-fiction"],
	"politics": ["non-fiction"],
	"romance": ["fiction"],
	"sci-fi": ["fiction"],
	"self-help": ["reference"],
	"social-sciences": ["non-fiction"],
	"spirituality": ["non-fiction"],
	"technology": ["non-fiction"],
	"textbook": ["reference"],
	"thesaurus": ["reference"],
	"thriller": ["fiction"],
	"travel": ["non-fiction"],
	"western": ["fiction"],
	"comics": ["fiction"]
} as const;
export const BookGenres = z.nativeEnum(bookGenres);
export type BookGenres = z.infer<typeof BookGenres>;