import { z } from "zod";
export const collectionNames = {
	"Admin Task": "adminTask",
	"Album": "album",
	"Barcode": "barcode",
	"Barcode Generator": "barcodeGenerator",
	"Book": "book",
	"Brand": "brand",
	"Classifier": "classifier",
	"Dropdown": "dropdown",
	"Facility": "facility",
	"Hash Tag": "hashTag",
	"Media Collection": "mediaCollection",
	"Mercari Brand": "mercariBrand",
	"Mercari Taxonomy": "mercariTaxonomy",
	"Movie": "movie",
	"Person": "person",
	"Product Line": "productLine",
	"Self Storage": "selfStorage",
	"Settings": "settings",
	"TV Series": "tvSeries",
	"Video Game": "videoGame",
	"Address": "address",
	"TV Episode": "tvEpisode",
	"Dimension": "dimension",
	"Product": "product",
	"Product Image": "productImage",
	"Binary File": "binaryFile",
	"Sku": "sku",
	"Color": "color",
	"Operating System": "operatingSystem",
	"FabricMadeOf": "fabricMadeOf",
	"MaterialsMadeOf": "materialsMadeOf"
} as const;
export const collectionNamesToGroup = {
	"adminTask": ["reference"],
	"album": ["reference"],
	"barcode": ["reference"],
	"barcodeGenerator": ["reference"],
	"book": ["reference"],
	"brand": ["reference"],
	"classifier": ["reference"],
	"dropdown": ["reference"],
	"facility": ["reference"],
	"hashTag": ["reference"],
	"mediaCollection": ["reference"],
	"mercariBrand": ["reference"],
	"mercariTaxonomy": ["reference"],
	"movie": ["reference"],
	"person": ["reference"],
	"productLine": ["reference"],
	"selfStorage": ["reference"],
	"settings": ["reference"],
	"tvSeries": ["reference"],
	"videoGame": ["reference"],
	"address": ["embedded"],
	"tvEpisode": ["embedded"],
	"dimension": ["embedded"],
	"product": ["reference"],
	"productImage": ["reference"],
	"binaryFile": ["embedded"],
	"sku": ["reference"],
	"color": ["embedded"],
	"operatingSystem": ["embedded"],
	"fabricMadeOf": ["embedded"],
	"materialsMadeOf": ["embedded"]
} as const;
export const CollectionNames = z.nativeEnum(collectionNames);
export type CollectionNames = z.infer<typeof CollectionNames>;