import { z } from "zod";
export const emmyAwardCategories = {
	"Outstanding Comedy Series": "comedy",
	"Outstanding Drama Series": "drama",
	"Outstanding Limited/Anthology Series": "limited",
	"Outstanding Reality Competition": "reality",
	"Outstanding Scripted Variety Series": "variety",
	"Outstanding Talk Series": "talk",
	"Outstanding Television Movie": "movie",
	"Outstanding Directing for a Comedy Series": "directing-comedy",
	"Outstanding Directing for a Drama Series": "directing-drama",
	"Outstanding Directing for a Limited/Anthology Series": "directing-limited",
	"Outstanding Directing for a Variety Series": "directing-variety",
	"Outstanding Writing for a Comedy Series": "writing-comedy",
	"Outstanding Writing for a Drama Series": "writing-drama",
	"Outstanding Writing for a Limited/Anthology Series": "writing-limited",
	"Outstanding Writing for a Variety Series": "writing-variety",
	"Outstanding Lead Actor in a Comedy Series": "actor-comedy",
	"Outstanding Lead Actor in a Drama Series": "actor-drama",
	"Outstanding Lead Actor in a Limited/Anthology Series": "actor-limited",
	"Outstanding Lead Actress in a Comedy Series": "actress-comedy",
	"Outstanding Lead Actress in a Drama Series": "actress-drama",
	"Outstanding Lead Actress in a Limited/Anthology Series": "actress-limited",
	"Outstanding Supporting Actor in a Comedy Series": "supporting-actor-comedy",
	"Outstanding Supporting Actor in a Drama Series": "supporting-actor-drama",
	"Outstanding Supporting Actor in a Limited/Anthology Series": "supporting-actor-limited",
	"Outstanding Supporting Actress in a Comedy Series": "supporting-actress-comedy",
	"Outstanding Supporting Actress in a Drama Series": "supporting-actress-drama",
	"Outstanding Supporting Actress in a Limited/Anthology Series": "supporting-actress-limited",
	"Outstanding Documentary or Nonfiction Series": "documentary-series",
	"Outstanding Documentary or Nonfiction Special": "documentary-special",
	"Outstanding Animated Program": "animated"
} as const;
export const emmyAwardCategoriesToGroup = {
	"comedy": ["emmy"],
	"drama": ["emmy"],
	"limited": ["emmy"],
	"reality": ["emmy"],
	"variety": ["emmy"],
	"talk": ["emmy"],
	"movie": ["emmy"],
	"directing-comedy": ["emmy"],
	"directing-drama": ["emmy"],
	"directing-limited": ["emmy"],
	"directing-variety": ["emmy"],
	"writing-comedy": ["emmy"],
	"writing-drama": ["emmy"],
	"writing-limited": ["emmy"],
	"writing-variety": ["emmy"],
	"actor-comedy": ["emmy"],
	"actor-drama": ["emmy"],
	"actor-limited": ["emmy"],
	"actress-comedy": ["emmy"],
	"actress-drama": ["emmy"],
	"actress-limited": ["emmy"],
	"supporting-actor-comedy": ["emmy"],
	"supporting-actor-drama": ["emmy"],
	"supporting-actor-limited": ["emmy"],
	"supporting-actress-comedy": ["emmy"],
	"supporting-actress-drama": ["emmy"],
	"supporting-actress-limited": ["emmy"],
	"documentary-series": ["emmy"],
	"documentary-special": ["emmy"],
	"animated": ["emmy"]
} as const;
export const EmmyAwardCategories = z.nativeEnum(emmyAwardCategories);
export type EmmyAwardCategories = z.infer<typeof EmmyAwardCategories>;