import { z } from "zod";
export const proSportsTeams = {
	"Arizona Diamondbacks": "mlb-arizona",
	"Atlanta Braves": "mlb-atlanta",
	"Baltimore Orioles": "mlb-baltimore",
	"Boston Red Sox": "mlb-boston",
	"Chicago Cubs": "mlb-chicago-cubs",
	"Chicago White Sox": "mlb-chicago-sox",
	"Cincinnati Reds": "mlb-cincinnati",
	"Cleveland Guardians": "mlb-cleveland",
	"Colorado Rockies": "mlb-colorado",
	"Detroit Tigers": "mlb-detroit",
	"Houston Astros": "mlb-houston",
	"Kansas City Royals": "mlb-kansas-city",
	"Los Angeles Angels": "mlb-la-angels",
	"Los Angeles Dodgers": "mlb-la-dodgers",
	"Miami Marlins": "mlb-miami",
	"Milwaukee Brewers": "mlb-milwaukee",
	"Minnesota Twins": "mlb-minnesota",
	"New York Mets": "mlb-ny-mets",
	"New York Yankees": "mlb-ny-yankees",
	"Oakland Athletics": "mlb-oakland",
	"Philadelphia Phillies": "mlb-philadelphia",
	"Pittsburgh Pirates": "mlb-pittsburgh",
	"San Diego Padres": "mlb-san-diego",
	"San Francisco Giants": "mlb-san-francisco",
	"Seattle Mariners": "mlb-seattle",
	"St. Louis Cardinals": "mlb-st-louis",
	"Tampa Bay Rays": "mlb-tampa-bay",
	"Texas Rangers": "mlb-texas",
	"Toronto Blue Jays": "mlb-toronto",
	"Washington Nationals": "mlb-washington",
	"Atlanta Hawks": "nba-atlanta",
	"Boston Celtics": "nba-boston",
	"Brooklyn Nets": "nba-brooklyn",
	"Charlotte Hornets": "nba-charlotte",
	"Chicago Bulls": "nba-chicago",
	"Cleveland Cavaliers": "nba-cleveland",
	"Dallas Mavericks": "nba-dallas",
	"Denver Nuggets": "nba-denver",
	"Detroit Pistons": "nba-detroit",
	"Golden State Warriors": "nba-golden-state",
	"Houston Rockets": "nba-houston",
	"Indiana Pacers": "nba-indiana",
	"Los Angeles Clippers": "nba-la-clippers",
	"Los Angeles Lakers": "nba-la-lakers",
	"Memphis Grizzlies": "nba-memphis",
	"Miami Heat": "nba-miami",
	"Milwaukee Bucks": "nba-milwaukee",
	"Minnesota Timberwolves": "nba-minnesota",
	"New Orleans Pelicans": "nba-new-orleans",
	"New York Knicks": "nba-new-york",
	"Oklahoma City Thunder": "nba-oklahoma-city",
	"Orlando Magic": "nba-orlando",
	"Philadelphia 76ers": "nba-philadelphia",
	"Phoenix Suns": "nba-phoenix",
	"Portland Trail Blazers": "nba-portland-trail",
	"Sacramento Kings": "nba-sacramento",
	"San Antonio Spurs": "nba-san-antonio",
	"Toronto Raptors": "nba-toronto",
	"Utah Jazz": "nba-utah",
	"Washington Wizards": "nba-washington",
	"Arizona Cardinals": "nfl-arizona",
	"Atlanta Falcons": "nfl-atlanta",
	"Baltimore Ravens": "nfl-baltimore",
	"Buffalo Bills": "nfl-buffalo",
	"Carolina Panthers": "nfl-carolina",
	"Chicago Bears": "nfl-chicago",
	"Cincinnati Bengals": "nfl-cincinnati",
	"Cleveland Browns": "nfl-cleveland",
	"Dallas Cowboys": "nfl-dallas",
	"Denver Broncos": "nfl-denver",
	"Detroit Lions": "nfl-detroit",
	"Green Bay Packers": "nfl-green-bay",
	"Houston Texans": "nfl-houston",
	"Indianapolis Colts": "nfl-indianapolis",
	"Jacksonville Jaguars": "nfl-jacksonville",
	"Kansas City Chiefs": "nfl-kansas-city",
	"Los Angeles Chargers": "nfl-la-chargers",
	"Los Angeles Rams": "nfl-la-rams",
	"Las Vegas Raiders": "nfl-las-vegas",
	"Miami Dolphins": "nfl-miami",
	"Minnesota Vikings": "nfl-minnesota",
	"New England Patriots": "nfl-new-england",
	"New Orleans Saints": "nfl-new-orleans",
	"New York Giants": "nfl-ny-giants",
	"New York Jets": "nfl-ny-jets",
	"Philadelphia Eagles": "nfl-philadelphia",
	"Pittsburgh Steelers": "nfl-pittsburgh",
	"San Francisco 49ers": "nfl-san-francisco",
	"Seattle Seahawks": "nfl-seattle",
	"Tampa Bay Buccaneers": "nfl-tampa-bay",
	"Tennessee Titans": "nfl-tennessee",
	"Washington Commanders": "nfl-washington",
	"Anaheim Ducks": "nhl-anaheim",
	"Boston Bruins": "nhl-boston",
	"Buffalo Sabres": "nhl-buffalo",
	"Calgary Flames": "nhl-calgary",
	"Carolina Hurricanes": "nhl-carolina",
	"Chicago Blackhawks": "nhl-chicago",
	"Colorado Avalanche": "nhl-colorado",
	"Columbus Blue Jackets": "nhl-columbus",
	"Dallas Stars": "nhl-dallas",
	"Detroit Red Wings": "nhl-detroit",
	"Edmonton Oilers": "nhl-edmonton",
	"Florida Panthers": "nhl-florida",
	"Los Angeles Kings": "nhl-los-angeles",
	"Minnesota Wild": "nhl-minnesota",
	"Montreal Canadiens": "nhl-montreal",
	"Nashville Predators": "nhl-nashville",
	"New Jersey Devils": "nhl-new-jersey",
	"New York Islanders": "nhl-ny-islanders",
	"New York Rangers": "nhl-ny-rangers",
	"Ottawa Senators": "nhl-ottawa",
	"Philadelphia Flyers": "nhl-philadelphia",
	"Pittsburgh Penguins": "nhl-pittsburgh",
	"San Jose Sharks": "nhl-san-jose",
	"Seattle Kraken": "nhl-seattle",
	"St. Louis Blues": "nhl-st-louis",
	"Tampa Bay Lightning": "nhl-tampa-bay",
	"Toronto Maple Leafs": "nhl-toronto",
	"Utah Hockey Club": "nhl-utah",
	"Vancouver Canucks": "nhl-vancouver",
	"Vegas Golden Knights": "nhl-vegas",
	"Washington Capitals": "nhl-washington",
	"Winnipeg Jets": "nhl-winnipeg",
	"Atlanta United FC": "mls-atlanta",
	"Charlotte FC": "mls-charlotte",
	"Chicago Fire FC": "mls-chicago",
	"FC Cincinnati": "mls-cincinnati",
	"Columbus Crew": "mls-columbus",
	"D.C. United": "mls-dc",
	"Inter Miami CF": "mls-miami",
	"CF Montréal": "mls-montreal",
	"Nashville SC": "mls-nashville",
	"New England Revolution": "mls-new-england",
	"New York City FC": "mls-nyc",
	"New York Red Bulls": "mls-ny-red-bulls",
	"Orlando City SC": "mls-orlando",
	"Philadelphia Union": "mls-philadelphia",
	"Toronto FC": "mls-toronto",
	"Austin FC": "mls-austin",
	"Colorado Rapids": "mls-colorado",
	"FC Dallas": "mls-dallas",
	"Houston Dynamo FC": "mls-houston",
	"LA Galaxy": "mls-la-galaxy",
	"Los Angeles FC": "mls-la-fc",
	"Minnesota United FC": "mls-minnesota",
	"Portland Timbers": "mls-portland",
	"Real Salt Lake": "mls-salt-lake",
	"San Diego FC": "mls-san-diego",
	"San Jose Earthquakes": "mls-san-jose",
	"Seattle Sounders FC": "mls-seattle",
	"Sporting Kansas City": "mls-kansas-city",
	"St. Louis City SC": "mls-st-louis",
	"Vancouver Whitecaps FC": "mls-vancouver",
	"Atlanta Dream": "wnba-atlanta",
	"Chicago Sky": "wnba-chicago",
	"Connecticut Sun": "wnba-connecticut",
	"Indiana Fever": "wnba-indiana",
	"New York Liberty": "wnba-new-york",
	"Washington Mystics": "wnba-washington",
	"Dallas Wings": "wnba-dallas",
	"Golden State Valkyries": "wnba-golden-state",
	"Las Vegas Aces": "wnba-las-vegas",
	"Los Angeles Sparks": "wnba-los-angeles",
	"Minnesota Lynx": "wnba-minnesota",
	"Phoenix Mercury": "wnba-phoenix",
	"Seattle Storm": "wnba-seattle"
} as const;
export const proSportsTeamsToRegex = {
	"mlb-arizona": "(arizona|az).*diamondback",
	"mlb-atlanta": "(atlanta|atl).*brave",
	"mlb-baltimore": "(baltimore|blt).*oriole",
	"mlb-boston": "(boston|bos).*red.*sox",
	"mlb-chicago-cubs": "(chicago|chi).*cubs",
	"mlb-chicago-sox": "(chicago|chi).*white.*sox",
	"mlb-cincinnati": "(cincinnati|cin).*red",
	"mlb-cleveland": "(cleveland|cle).*guardian",
	"mlb-colorado": "(colorado|co).*rockies",
	"mlb-detroit": "(detroit|det).*tiger",
	"mlb-houston": "(houston|hou).*astro",
	"mlb-kansas-city": "(kansas.*city|kc).*royal",
	"mlb-la-angels": "(los.*angeles|la).*angel",
	"mlb-la-dodgers": "(los.*angeles|la).*dodger",
	"mlb-miami": "(miami|mia).*marlin",
	"mlb-milwaukee": "(milwaukee|mke).*brewer",
	"mlb-minnesota": "(minnesota|mn).*twin",
	"mlb-ny-mets": "(new.*york|ny).*mets",
	"mlb-ny-yankees": "(new.*york|ny).*yankee",
	"mlb-oakland": "(oakland|oak).*athletic",
	"mlb-philadelphia": "(philadelphia|phl).*phill",
	"mlb-pittsburgh": "(pittsburg|pgh).*pirate",
	"mlb-san-diego": "(san.*diego|sd).*padre",
	"mlb-san-francisco": "(san.*franc|sf).*giant",
	"mlb-seattle": "(seattle|sea).*mariner",
	"mlb-st-louis": "(saint|st).*louis.*cardinal",
	"mlb-tampa-bay": "(tampa.*bay|tb).*ray",
	"mlb-texas": "(texas|tx).*ranger",
	"mlb-toronto": "(toronto|tor).*blue.*jay",
	"mlb-washington": "(washington|dc).*national",
	"nba-atlanta": "(atlanta|atl).*hawk",
	"nba-boston": "(boston|bos).*celtic",
	"nba-brooklyn": "brooklyn.*net",
	"nba-charlotte": "(charlotte|clt).*hornet",
	"nba-chicago": "(chicago|chi).*bull",
	"nba-cleveland": "(cleveland|cle).*cavalier",
	"nba-dallas": "(dallas|dal).*maverick",
	"nba-denver": "(denver|den).*nugget",
	"nba-detroit": "(detroit|det).*piston",
	"nba-golden-state": "(golden.*(state|st)|ca).*warrior",
	"nba-houston": "(houston|hou).*rocket",
	"nba-indiana": "(indiana|in).*pacer",
	"nba-la-clippers": "(los.*angeles|la).*clipper",
	"nba-la-lakers": "(los.*angeles|la).*laker",
	"nba-memphis": "(memphis|mem).*grizzl",
	"nba-miami": "(miami|mia).*heat",
	"nba-milwaukee": "(milwaukee|mil).*buck",
	"nba-minnesota": "(minnesota|mn).*timberwol",
	"nba-new-orleans": "(new.*orleans|nola|no).*pelican",
	"nba-new-york": "(new.*york|ny).*knick",
	"nba-oklahoma-city": "(oklahoma.*city|okc).*thunder",
	"nba-orlando": "(orlando|orl).*magic",
	"nba-philadelphia": "(philadelphia|phl).*76er",
	"nba-phoenix": "(phoenix|phx).*sun",
	"nba-portland-trail": "(portland|pdx).*trailblaze",
	"nba-sacramento": "(sacramento|sac).*king",
	"nba-san-antonio": "(san.*antonio|sa).*spur",
	"nba-toronto": "(toronto|tor).*raptor",
	"nba-utah": "(utah|ut).*jazz",
	"nba-washington": "(washington|dc).*wizard",
	"nfl-arizona": "(arizona|az).*cardinal",
	"nfl-atlanta": "(atlanta|atl).*falcon",
	"nfl-baltimore": "(baltimore|blt).*raven",
	"nfl-buffalo": "(buffalo|buf).*bill",
	"nfl-carolina": "(carolina|nc).*panther",
	"nfl-chicago": "(chicago|chi).*bear",
	"nfl-cincinnati": "(cincinnati|cin).*bengal",
	"nfl-cleveland": "(cleveland|cle).*brown",
	"nfl-dallas": "(dallas|dal).*cowboy",
	"nfl-denver": "(denver|den).*bronco",
	"nfl-detroit": "(detroit|det).*lion",
	"nfl-green-bay": "(green.*bay|gb).*packer",
	"nfl-houston": "(houston|hou).*texan",
	"nfl-indianapolis": "(indianapolis|ind).*colt",
	"nfl-jacksonville": "(jacksonville|jax).*jaguar",
	"nfl-kansas-city": "(kansas.*city|kc).*chief",
	"nfl-la-chargers": "(los.*angeles|la).*charger",
	"nfl-la-rams": "(los.*angeles|la).*ram",
	"nfl-las-vegas": "(las.*vegas).*raider",
	"nfl-miami": "(miami|mia).*dolphin",
	"nfl-minnesota": "(minnesota|mn).*viking",
	"nfl-new-england": "(new.*england|ne).*patriot",
	"nfl-new-orleans": "(new.*orleans|nola).*saint",
	"nfl-ny-giants": "(new.*york|ny).*giant",
	"nfl-ny-jets": "(new.*york|ny).*jet",
	"nfl-philadelphia": "(philadelphia|phl).*eagle",
	"nfl-pittsburgh": "(pittsburgh|pgh).*steeler",
	"nfl-san-francisco": "(san.*francicso|sf).*49er",
	"nfl-seattle": "(seattle|sea).*seahawk",
	"nfl-tampa-bay": "(tampa.*bay|tb).*buccaneer",
	"nfl-tennessee": "(tennessee|tn).*titan",
	"nfl-washington": "(washington|dc).*commander",
	"nhl-anaheim": "(anaheim|ana).*duck",
	"nhl-boston": "(boston|bos).*bruin",
	"nhl-buffalo": "(buffalo|buf).*sabre",
	"nhl-calgary": "(calgary|cgy).*flame",
	"nhl-carolina": "(carolina|nc).*hurricane",
	"nhl-chicago": "(chicago|chi).*blackhawk",
	"nhl-colorado": "(colorado|co).*avalanche",
	"nhl-columbus": "(columbus|cbj).*blue.*jacket",
	"nhl-dallas": "(dallas|dal).*star",
	"nhl-detroit": "(detroit|det).*red.*wing",
	"nhl-edmonton": "(edmonton|edm).*oiler",
	"nhl-florida": "(florida|fl).*panther",
	"nhl-los-angeles": "(los.*angeles|la).*king",
	"nhl-minnesota": "(minnesota|mn).*wild",
	"nhl-montreal": "(montreal|mtl).*canadien",
	"nhl-nashville": "(nashville|nsh).*predator",
	"nhl-new-jersey": "(new.*jersey|nj).*devil",
	"nhl-ny-islanders": "(new.*york|ny).*islander",
	"nhl-ny-rangers": "(new.*york|ny).*ranger",
	"nhl-ottawa": "(ottawa|ott).*senator",
	"nhl-philadelphia": "(philadelphia|phl).*flyer",
	"nhl-pittsburgh": "(pittsburgh|pgh).*penguin",
	"nhl-san-jose": "(san.*jose|sj).*shark",
	"nhl-seattle": "(seattle|sea).*kraken",
	"nhl-st-louis": "((st|saint).*louis|stl).*blue",
	"nhl-tampa-bay": "(tampa.*bay|tb).*lightning",
	"nhl-toronto": "(toronto|tor).*maple.*leaf",
	"nhl-utah": "(utah|ut).*hockey.*club",
	"nhl-vancouver": "(vancouver|van).*canuck",
	"nhl-vegas": "(las.*vegas|las|lv).*golden.*knight",
	"nhl-washington": "(washington|dc).*capital",
	"nhl-winnipeg": "(winnipeg|wpg).*jet",
	"mls-atlanta": "(atlant|atl).*united",
	"mls-charlotte": "charlotte.*fc",
	"mls-chicago": "chicago.*fire",
	"mls-cincinnati": "(cincinnati|cin).*fc|knifey.*lion",
	"mls-columbus": "(columbus|cmh).*crew",
	"mls-dc": "dc.*united.*eagle",
	"mls-miami": "inter.*(miami|mia).*cf.*heron",
	"mls-montreal": "cf.*(montreal|mtl).*impact",
	"mls-nashville": "(nashville|nsh).*sc.*coyote",
	"mls-new-england": "(new.*england|ne).*rev.*",
	"mls-nyc": "(new.*york.*(city)?|nyc).*fc.*pigeon",
	"mls-ny-red-bulls": "(new.*york).*red.*bull",
	"mls-orlando": "(orlando|orl).*city.*sc.*lion",
	"mls-philadelphia": "(philadelphia|phl).*union",
	"mls-toronto": "(toronto|tor).*red",
	"mls-austin": "(austin|aus).*fc.*los.*verde",
	"mls-colorado": "(colorado|co).*rapid",
	"mls-dallas": "fc.*(dallas|dal).*toro",
	"mls-houston": "(houston|hou).*dynamo.*fc",
	"mls-la-galaxy": "(los.*angeles|la).*galaxy",
	"mls-la-fc": "(los.*angeles|la).*fc",
	"mls-minnesota": "(minnesota|mn).*united.*fc",
	"mls-portland": "(portland|pdx).*timber",
	"mls-salt-lake": "real.*(salt.*lake|slc)",
	"mls-san-diego": "(san.*diego|sd).*fc",
	"mls-san-jose": "(san.*jose|sj).*earthquake",
	"mls-seattle": "(seattle|sea).*sounder.*fc",
	"mls-kansas-city": "sporting.*(kansas.*city|kc)",
	"mls-st-louis": "((st|saint).*louis|stl).*city.*sc",
	"mls-vancouver": "(vancouver|van).*whitecap.*fc",
	"wnba-atlanta": "(atlanta|atl).*dream",
	"wnba-chicago": "(chicago|chi).*sky",
	"wnba-connecticut": "(connecticut|ct).*sun",
	"wnba-indiana": "(indiana|in).*fever",
	"wnba-new-york": "(new.*york|ny).*libery",
	"wnba-washington": "(washington|dc).*mystic",
	"wnba-dallas": "(dallas|dal).*wing",
	"wnba-golden-state": "(golden.*(state|st)|ca).*valkyr",
	"wnba-las-vegas": "(las.*vegas|lv|vegas).*ace",
	"wnba-los-angeles": "(los.*angeles|la).*spark",
	"wnba-minnesota": "(minnesota|mn).*lynx",
	"wnba-phoenix": "(phoenix|phx).*mercury",
	"wnba-seattle": "(seattle|sea).*storm"
} as const;
export const proSportsTeamsToGroup = {
	"mlb-arizona": ["mlb"],
	"mlb-atlanta": ["mlb"],
	"mlb-baltimore": ["mlb"],
	"mlb-boston": ["mlb"],
	"mlb-chicago-cubs": ["mlb"],
	"mlb-chicago-sox": ["mlb"],
	"mlb-cincinnati": ["mlb"],
	"mlb-cleveland": ["mlb"],
	"mlb-colorado": ["mlb"],
	"mlb-detroit": ["mlb"],
	"mlb-houston": ["mlb"],
	"mlb-kansas-city": ["mlb"],
	"mlb-la-angels": ["mlb"],
	"mlb-la-dodgers": ["mlb"],
	"mlb-miami": ["mlb"],
	"mlb-milwaukee": ["mlb"],
	"mlb-minnesota": ["mlb"],
	"mlb-ny-mets": ["mlb"],
	"mlb-ny-yankees": ["mlb"],
	"mlb-oakland": ["mlb"],
	"mlb-philadelphia": ["mlb"],
	"mlb-pittsburgh": ["mlb"],
	"mlb-san-diego": ["mlb"],
	"mlb-san-francisco": ["mlb"],
	"mlb-seattle": ["mlb"],
	"mlb-st-louis": ["mlb"],
	"mlb-tampa-bay": ["mlb"],
	"mlb-texas": ["mlb"],
	"mlb-toronto": ["mlb"],
	"mlb-washington": ["mlb"],
	"nba-atlanta": ["nba"],
	"nba-boston": ["nba"],
	"nba-brooklyn": ["nba"],
	"nba-charlotte": ["nba"],
	"nba-chicago": ["nba"],
	"nba-cleveland": ["nba"],
	"nba-dallas": ["nba"],
	"nba-denver": ["nba"],
	"nba-detroit": ["nba"],
	"nba-golden-state": ["nba"],
	"nba-houston": ["nba"],
	"nba-indiana": ["nba"],
	"nba-la-clippers": ["nba"],
	"nba-la-lakers": ["nba"],
	"nba-memphis": ["nba"],
	"nba-miami": ["nba"],
	"nba-milwaukee": ["nba"],
	"nba-minnesota": ["nba"],
	"nba-new-orleans": ["nba"],
	"nba-new-york": ["nba"],
	"nba-oklahoma-city": ["nba"],
	"nba-orlando": ["nba"],
	"nba-philadelphia": ["nba"],
	"nba-phoenix": ["nba"],
	"nba-portland-trail": ["nba"],
	"nba-sacramento": ["nba"],
	"nba-san-antonio": ["nba"],
	"nba-toronto": ["nba"],
	"nba-utah": ["nba"],
	"nba-washington": ["nba"],
	"nfl-arizona": ["nfl"],
	"nfl-atlanta": ["nfl"],
	"nfl-baltimore": ["nfl"],
	"nfl-buffalo": ["nfl"],
	"nfl-carolina": ["nfl"],
	"nfl-chicago": ["nfl"],
	"nfl-cincinnati": ["nfl"],
	"nfl-cleveland": ["nfl"],
	"nfl-dallas": ["nfl"],
	"nfl-denver": ["nfl"],
	"nfl-detroit": ["nfl"],
	"nfl-green-bay": ["nfl"],
	"nfl-houston": ["nfl"],
	"nfl-indianapolis": ["nfl"],
	"nfl-jacksonville": ["nfl"],
	"nfl-kansas-city": ["nfl"],
	"nfl-la-chargers": ["nfl"],
	"nfl-la-rams": ["nfl"],
	"nfl-las-vegas": ["nfl"],
	"nfl-miami": ["nfl"],
	"nfl-minnesota": ["nfl"],
	"nfl-new-england": ["nfl"],
	"nfl-new-orleans": ["nfl"],
	"nfl-ny-giants": ["nfl"],
	"nfl-ny-jets": ["nfl"],
	"nfl-philadelphia": ["nfl"],
	"nfl-pittsburgh": ["nfl"],
	"nfl-san-francisco": ["nfl"],
	"nfl-seattle": ["nfl"],
	"nfl-tampa-bay": ["nfl"],
	"nfl-tennessee": ["nfl"],
	"nfl-washington": ["nfl"],
	"nhl-anaheim": ["nhl"],
	"nhl-boston": ["nhl"],
	"nhl-buffalo": ["nhl"],
	"nhl-calgary": ["nhl"],
	"nhl-carolina": ["nhl"],
	"nhl-chicago": ["nhl"],
	"nhl-colorado": ["nhl"],
	"nhl-columbus": ["nhl"],
	"nhl-dallas": ["nhl"],
	"nhl-detroit": ["nhl"],
	"nhl-edmonton": ["nhl"],
	"nhl-florida": ["nhl"],
	"nhl-los-angeles": ["nhl"],
	"nhl-minnesota": ["nhl"],
	"nhl-montreal": ["nhl"],
	"nhl-nashville": ["nhl"],
	"nhl-new-jersey": ["nhl"],
	"nhl-ny-islanders": ["nhl"],
	"nhl-ny-rangers": ["nhl"],
	"nhl-ottawa": ["nhl"],
	"nhl-philadelphia": ["nhl"],
	"nhl-pittsburgh": ["nhl"],
	"nhl-san-jose": ["nhl"],
	"nhl-seattle": ["nhl"],
	"nhl-st-louis": ["nhl"],
	"nhl-tampa-bay": ["nhl"],
	"nhl-toronto": ["nhl"],
	"nhl-utah": ["nhl"],
	"nhl-vancouver": ["nhl"],
	"nhl-vegas": ["nhl"],
	"nhl-washington": ["nhl"],
	"nhl-winnipeg": ["nhl"],
	"mls-atlanta": ["mls"],
	"mls-charlotte": ["mls"],
	"mls-chicago": ["mls"],
	"mls-cincinnati": ["mls"],
	"mls-columbus": ["mls"],
	"mls-dc": ["mls"],
	"mls-miami": ["mls"],
	"mls-montreal": ["mls"],
	"mls-nashville": ["mls"],
	"mls-new-england": ["mls"],
	"mls-nyc": ["mls"],
	"mls-ny-red-bulls": ["mls"],
	"mls-orlando": ["mls"],
	"mls-philadelphia": ["mls"],
	"mls-toronto": ["mls"],
	"mls-austin": ["mls"],
	"mls-colorado": ["mls"],
	"mls-dallas": ["mls"],
	"mls-houston": ["mls"],
	"mls-la-galaxy": ["mls"],
	"mls-la-fc": ["mls"],
	"mls-minnesota": ["mls"],
	"mls-portland": ["mls"],
	"mls-salt-lake": ["mls"],
	"mls-san-diego": ["mls"],
	"mls-san-jose": ["mls"],
	"mls-seattle": ["mls"],
	"mls-kansas-city": ["mls"],
	"mls-st-louis": ["mls"],
	"mls-vancouver": ["mls"],
	"wnba-atlanta": ["wnba"],
	"wnba-chicago": ["wnba"],
	"wnba-connecticut": ["wnba"],
	"wnba-indiana": ["wnba"],
	"wnba-new-york": ["wnba"],
	"wnba-washington": ["wnba"],
	"wnba-dallas": ["wnba"],
	"wnba-golden-state": ["wnba"],
	"wnba-las-vegas": ["wnba"],
	"wnba-los-angeles": ["wnba"],
	"wnba-minnesota": ["wnba"],
	"wnba-phoenix": ["wnba"],
	"wnba-seattle": ["wnba"]
} as const;
export const ProSportsTeams = z.nativeEnum(proSportsTeams);
export type ProSportsTeams = z.infer<typeof ProSportsTeams>;