import { z } from "zod";
export const provinces = {
	"Alberta": "AB",
	"Alaska": "AK",
	"Alabama": "AL",
	"Arkansas": "AR",
	"Arizona": "AZ",
	"British Columbia": "BC",
	"California": "CA",
	"Colorado": "CO",
	"Connecticut": "CT",
	"District of Columbia": "DC",
	"Deleware": "DE",
	"Florida": "FL",
	"Georgia": "GA",
	"Hawaii": "HI",
	"Iowa": "IA",
	"Idaho": "ID",
	"Illinois": "IL",
	"Indiana": "IN",
	"Kansas": "KS",
	"Kentucky": "KY",
	"Louisiana": "LA",
	"Massachusettes": "MA",
	"Manitoba": "MB",
	"Maryland": "MD",
	"Maine": "ME",
	"Michigan": "MI",
	"Minnesota": "MN",
	"Missouri": "MO",
	"Mississippi": "MS",
	"Montana": "MT",
	"New Brunswick": "NB",
	"North Carolina": "NC",
	"North Dakota": "ND",
	"Nebraska": "NE",
	"New Hampshire": "NH",
	"New Jersey": "NJ",
	"Newfoundland and Labrador": "NL",
	"New Mexico": "NM",
	"Nova Scotia": "NS",
	"Northwest Territory": "NT",
	"Nunavut": "NU",
	"Nevada": "NV",
	"New York": "NY",
	"Ohio": "OH",
	"Oklahoma": "OK",
	"Ontario": "ON",
	"Oregon": "OR",
	"Pennsylvania": "PA",
	"Prince Edward Island": "PE",
	"Puerto Rico": "PR",
	"Quebec": "QC",
	"Rhode Island": "RI",
	"South Carolina": "SC",
	"South Dakota": "SD",
	"Sasketchewan": "SK",
	"Tennessee": "TN",
	"Texas": "TX",
	"Utah": "UT",
	"Virginia": "VA",
	"Vermont": "VT",
	"Washington": "WA",
	"Wisconsin": "WI",
	"West Virginia": "WV",
	"Wyoming": "WY",
	"Yukon": "YT"
} as const;
export const provincesToGroup = {
	"AB": ["CA"],
	"AK": ["US"],
	"AL": ["US"],
	"AR": ["US"],
	"AZ": ["US"],
	"BC": ["CA"],
	"CA": ["US"],
	"CO": ["US"],
	"CT": ["US"],
	"DC": ["US"],
	"DE": ["US"],
	"FL": ["US"],
	"GA": ["US"],
	"HI": ["US"],
	"IA": ["US"],
	"ID": ["US"],
	"IL": ["US"],
	"IN": ["US"],
	"KS": ["US"],
	"KY": ["US"],
	"LA": ["US"],
	"MA": ["US"],
	"MB": ["CA"],
	"MD": ["US"],
	"ME": ["US"],
	"MI": ["US"],
	"MN": ["US"],
	"MO": ["US"],
	"MS": ["US"],
	"MT": ["US"],
	"NB": ["CA"],
	"NC": ["US"],
	"ND": ["US"],
	"NE": ["US"],
	"NH": ["US"],
	"NJ": ["US"],
	"NL": ["CA"],
	"NM": ["US"],
	"NS": ["CA"],
	"NT": ["CA"],
	"NU": ["CA"],
	"NV": ["US"],
	"NY": ["US"],
	"OH": ["US"],
	"OK": ["US"],
	"ON": ["CA"],
	"OR": ["US"],
	"PA": ["US"],
	"PE": ["CA"],
	"PR": ["US"],
	"QC": ["CA"],
	"RI": ["US"],
	"SC": ["US"],
	"SD": ["US"],
	"SK": ["CA"],
	"TN": ["US"],
	"TX": ["US"],
	"UT": ["US"],
	"VA": ["US"],
	"VT": ["US"],
	"WA": ["US"],
	"WI": ["US"],
	"WV": ["US"],
	"WY": ["US"],
	"YT": ["CA"]
} as const;
export const Provinces = z.nativeEnum(provinces);
export type Provinces = z.infer<typeof Provinces>;