import { z } from "zod";
export const videoConnectorTypes = {
	"Apple Display Connector": "apple-display-conn",
	"Coaxial (female)": "coaxial-f",
	"Coaxial (male)": "coaxial-m",
	"Component (female)": "component-f",
	"Component (male)": "component-m",
	"Displayport (female)": "displayport-f",
	"Displayport (male)": "displayport-m",
	"DVI-D Single": "div-d-single",
	"DVI-D Dual-DMS": "dvi-d-dual-dms",
	"DVI-D Dual": "dvi-d-dual",
	"DVI-I Dual": "dvi-i-dual",
	"DVI-I Single": "dvi-i-single",
	"HDMI Type A (female)": "hdmi-type-a-f",
	"HDMI Type A (male)": "hdmi-type-a-m",
	"Micro DVS": "micro-dvs",
	"Micro HDMI Type D": "micro-hdmi-type-d",
	"Mini Displayport (female)": "mini-displayport-f",
	"Mini Displayport (male)": "mini-displayport-m",
	"Mini DVS": "mini-dvs",
	"Mini HDMI Type C": "mini-hdmi-type-c",
	"RCA": "rca",
	"S-Video": "s-video",
	"SVGA (female)": "svga-f",
	"SVGA (male)": "svga-m"
} as const;
export const videoConnectorTypesToImage = {
	"apple-display-conn": "src/assets/images/enums/videoConnectorTypes/apple-display-conn.png",
	"coaxial-f": "src/assets/images/enums/videoConnectorTypes/coaxial-f.png",
	"coaxial-m": "src/assets/images/enums/videoConnectorTypes/coaxial-m.png",
	"component-f": "src/assets/images/enums/videoConnectorTypes/component-f.png",
	"component-m": "src/assets/images/enums/videoConnectorTypes/component-m.png",
	"displayport-f": "src/assets/images/enums/videoConnectorTypes/displayport-f.png",
	"displayport-m": "src/assets/images/enums/videoConnectorTypes/displayport-m.png",
	"div-d-single": "src/assets/images/enums/videoConnectorTypes/div-d-single.png",
	"dvi-d-dual-dms": "src/assets/images/enums/videoConnectorTypes/dvi-d-dual-dms.png",
	"dvi-d-dual": "src/assets/images/enums/videoConnectorTypes/dvi-d-dual.png",
	"dvi-i-dual": "src/assets/images/enums/videoConnectorTypes/dvi-i-dual.png",
	"dvi-i-single": "src/assets/images/enums/videoConnectorTypes/dvi-i-single.png",
	"hdmi-type-a-f": "src/assets/images/enums/videoConnectorTypes/hdmi-type-a-f.png",
	"hdmi-type-a-m": "src/assets/images/enums/videoConnectorTypes/hdmi-type-a-m.png",
	"micro-dvs": "src/assets/images/enums/videoConnectorTypes/micro-dvs.png",
	"micro-hdmi-type-d": "src/assets/images/enums/videoConnectorTypes/micro-hdmi-type-d.png",
	"mini-displayport-f": "src/assets/images/enums/videoConnectorTypes/mini-displayport-f.png",
	"mini-displayport-m": "src/assets/images/enums/videoConnectorTypes/mini-displayport-m.png",
	"mini-dvs": "src/assets/images/enums/videoConnectorTypes/mini-dvs.png",
	"mini-hdmi-type-c": "src/assets/images/enums/videoConnectorTypes/mini-hdmi-type-c.png",
	"rca": "src/assets/images/enums/videoConnectorTypes/rca.png",
	"s-video": "src/assets/images/enums/videoConnectorTypes/s-video.png",
	"svga-f": "src/assets/images/enums/videoConnectorTypes/svga-f.png",
	"svga-m": "src/assets/images/enums/videoConnectorTypes/svga-m.png"
} as const;
export const VideoConnectorTypes = z.nativeEnum(videoConnectorTypes);
export type VideoConnectorTypes = z.infer<typeof VideoConnectorTypes>;