/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DataImport } from './routes/data'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DataIndexImport } from './routes/data.index'
import { Route as DataCollectionImport } from './routes/data.$collection'
import { Route as DataCollectionIndexImport } from './routes/data.$collection.index'

// Create/Update Routes

const DataRoute = DataImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DataIndexRoute = DataIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataRoute,
} as any)

const DataCollectionRoute = DataCollectionImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => DataRoute,
} as any)

const DataCollectionIndexRoute = DataCollectionIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataCollectionRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataImport
      parentRoute: typeof rootRoute
    }
    '/data/$collection': {
      id: '/data/$collection'
      path: '/$collection'
      fullPath: '/data/$collection'
      preLoaderRoute: typeof DataCollectionImport
      parentRoute: typeof DataImport
    }
    '/data/': {
      id: '/data/'
      path: '/'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexImport
      parentRoute: typeof DataImport
    }
    '/data/$collection/': {
      id: '/data/$collection/'
      path: '/'
      fullPath: '/data/$collection/'
      preLoaderRoute: typeof DataCollectionIndexImport
      parentRoute: typeof DataCollectionImport
    }
  }
}

// Create and export the route tree

interface DataCollectionRouteChildren {
  DataCollectionIndexRoute: typeof DataCollectionIndexRoute
}

const DataCollectionRouteChildren: DataCollectionRouteChildren = {
  DataCollectionIndexRoute: DataCollectionIndexRoute,
}

const DataCollectionRouteWithChildren = DataCollectionRoute._addFileChildren(
  DataCollectionRouteChildren,
)

interface DataRouteChildren {
  DataCollectionRoute: typeof DataCollectionRouteWithChildren
  DataIndexRoute: typeof DataIndexRoute
}

const DataRouteChildren: DataRouteChildren = {
  DataCollectionRoute: DataCollectionRouteWithChildren,
  DataIndexRoute: DataIndexRoute,
}

const DataRouteWithChildren = DataRoute._addFileChildren(DataRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data': typeof DataRouteWithChildren
  '/data/$collection': typeof DataCollectionRouteWithChildren
  '/data/': typeof DataIndexRoute
  '/data/$collection/': typeof DataCollectionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data': typeof DataIndexRoute
  '/data/$collection': typeof DataCollectionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data': typeof DataRouteWithChildren
  '/data/$collection': typeof DataCollectionRouteWithChildren
  '/data/': typeof DataIndexRoute
  '/data/$collection/': typeof DataCollectionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/data'
    | '/data/$collection'
    | '/data/'
    | '/data/$collection/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/data' | '/data/$collection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/data'
    | '/data/$collection'
    | '/data/'
    | '/data/$collection/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DataRoute: typeof DataRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DataRoute: DataRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/data"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/data": {
      "filePath": "data.tsx",
      "children": [
        "/data/$collection",
        "/data/"
      ]
    },
    "/data/$collection": {
      "filePath": "data.$collection.tsx",
      "parent": "/data",
      "children": [
        "/data/$collection/"
      ]
    },
    "/data/": {
      "filePath": "data.index.tsx",
      "parent": "/data"
    },
    "/data/$collection/": {
      "filePath": "data.$collection.index.tsx",
      "parent": "/data/$collection"
    }
  }
}
ROUTE_MANIFEST_END */
