import { z } from "zod";
export const grammyAwardCategories = {
	"Album of the Year": "album",
	"Record of the Year": "record",
	"Song of the Year": "song",
	"Best New Artist of the Year": "artist",
	"Songwriter of the Year": "songwriter",
	"Producer of the Year": "producer",
	"Best Pop Solo Performance": "pop-solo",
	"Best Pop Duo/Group Performance": "pop-duo",
	"Best Pop Vocal Album": "pop-vocal",
	"Best Dance/Electronic Recording": "dance",
	"Best Dance Pop Recording": "dance-pop",
	"Best Dance/Electronic Album": "dance-album",
	"Best Remixed Recording": "remix",
	"Best Rock Performance": "rock",
	"Best Metal Performance": "metal",
	"Best Rock Song Performance": "rock-song",
	"Best Rock Album": "rock-album",
	"Best Alternative Music Performance": "alternative",
	"Best Alternative Music Album": "alternative-album",
	"Best R&B Performance": "rnb",
	"Best Traditional R&B Performance": "traditional-rnb",
	"Best R&B Song": "rnb-song",
	"Best Progressive R&B Album": "progressive-rnb",
	"Best R&B Album": "rnb-album",
	"Best Rap Performance": "rap",
	"Best Melodic Rap Performance": "melodic-rap",
	"Best Rap Song": "rap-song",
	"Best Rap Album": "rap-album",
	"Best Spoken Word Poetry Album": "spoken-word",
	"Best Musical Theatre Album": "musical-theatre",
	"Best Country Solo Performance": "country-solo",
	"Best Country Duo/Group Performance": "country-duo",
	"Best Country Song": "country-song",
	"Best Country Album": "country-album",
	"Best Bluegrass Album": "bluegrass",
	"Best Folk Album": "folk",
	"Best Americana Album": "americana-album",
	"Best Americana Performance": "americana",
	"Best American Roots Performance": "american-roots",
	"Best Traditional Blues Album": "traditional-blues",
	"Best Contemporary Blues Album": "contemporary-blues",
	"Best Regional Roots Music Album": "regional-roots",
	"Best Gospel Performance/Song": "gospel",
	"Best Gospel Album": "gospel-album",
	"Best Contemporary Christian Music Performance/Song": "contemporary-christian",
	"Best Contemporary Christian Music Album": "contemporary-christian-album",
	"Best Traditional Pop Vocal Album": "traditional-pop",
	"Best Jazz Performance": "jazz",
	"Best Jazz Vocal Album": "jazz-vocal",
	"Best Jaxx Instrumental Album": "jazz-instrumental",
	"Best Large Jazz Ensemble Album": "large-jazz",
	"Best Latin Jazz Album": "latin-jazz",
	"Best Alternative Jazz Album": "alternative-jazz",
	"Best Latin Pop Album": "latin-pop",
	"Best Musica Urbana Album": "musica-urbana",
	"Best Latin Rock Album": "latin-rock",
	"Best Música Mexicana Album": "musica mexicana",
	"Best Tropical Latin Album": "tropical-latin",
	"Best Global Music Album": "global-music",
	"Best Reggae Album": "raggae",
	"Best New Age, Ambient, or Chant Album": "new-age",
	"Best Children's Music Album": "childrens",
	"Best Comedy Album": "comedy",
	"Best Audio Book, Narration & Storytelling Recording": "audio-book",
	"Best Compilation Soundtrack for Visual Media": "compilation",
	"Best Score Soundtrack Album for Visual Media": "soundtrack",
	"Best Score Soundtrack for Video Games and Other Interactive Media": "soundtrack-video-games",
	"Best Song Written for Visual Media": "song-visual-media",
	"Best Music Video": "music-video",
	"Best Music Film": "music-film"
} as const;
export const grammyAwardCategoriesToGroup = {
	"album": ["grammy"],
	"record": ["grammy"],
	"song": ["grammy"],
	"artist": ["grammy"],
	"songwriter": ["grammy"],
	"producer": ["grammy"],
	"pop-solo": ["grammy"],
	"pop-duo": ["grammy"],
	"pop-vocal": ["grammy"],
	"dance": ["grammy"],
	"dance-pop": ["grammy"],
	"dance-album": ["grammy"],
	"remix": ["grammy"],
	"rock": ["grammy"],
	"metal": ["grammy"],
	"rock-song": ["grammy"],
	"rock-album": ["grammy"],
	"alternative": ["grammy"],
	"alternative-album": ["grammy"],
	"rnb": ["grammy"],
	"traditional-rnb": ["grammy"],
	"rnb-song": ["grammy"],
	"progressive-rnb": ["grammy"],
	"rnb-album": ["grammy"],
	"rap": ["grammy"],
	"melodic-rap": ["grammy"],
	"rap-song": ["grammy"],
	"rap-album": ["grammy"],
	"spoken-word": ["grammy"],
	"musical-theatre": ["grammy"],
	"country-solo": ["grammy"],
	"country-duo": ["grammy"],
	"country-song": ["grammy"],
	"country-album": ["grammy"],
	"bluegrass": ["grammy"],
	"folk": ["grammy"],
	"americana-album": ["grammy"],
	"americana": ["grammy"],
	"american-roots": ["grammy"],
	"traditional-blues": ["grammy"],
	"contemporary-blues": ["grammy"],
	"regional-roots": ["grammy"],
	"gospel": ["grammy"],
	"gospel-album": ["grammy"],
	"contemporary-christian": ["grammy"],
	"contemporary-christian-album": ["grammy"],
	"traditional-pop": ["grammy"],
	"jazz": ["grammy"],
	"jazz-vocal": ["grammy"],
	"jazz-instrumental": ["grammy"],
	"large-jazz": ["grammy"],
	"latin-jazz": ["grammy"],
	"alternative-jazz": ["grammy"],
	"latin-pop": ["grammy"],
	"musica-urbana": ["grammy"],
	"latin-rock": ["grammy"],
	"musica mexicana": ["grammy"],
	"tropical-latin": ["grammy"],
	"global-music": ["grammy"],
	"raggae": ["grammy"],
	"new-age": ["grammy"],
	"childrens": ["grammy"],
	"comedy": ["grammy"],
	"audio-book": ["grammy"],
	"compilation": ["grammy"],
	"soundtrack": ["grammy"],
	"soundtrack-video-games": ["grammy"],
	"song-visual-media": ["grammy"],
	"music-video": ["grammy"],
	"music-film": ["grammy"]
} as const;
export const GrammyAwardCategories = z.nativeEnum(grammyAwardCategories);
export type GrammyAwardCategories = z.infer<typeof GrammyAwardCategories>;