import { z } from "zod";
export const portConnectorTypes = {
	"at-keyboard-f": "at-keyboard-f",
	"at-keyboard-m": "at-keyboard-m",
	"e-sata": "e-sata",
	"ethernet": "ethernet",
	"firewire-400": "firewire-400",
	"firewire-800": "firewire-800",
	"firewire": "firewire",
	"gameport": "gameport",
	"ide-40pin-port": "ide-40pin-port",
	"ide-40pin": "ide-40pin",
	"internal-50-pin-scsi-f": "internal-50-pin-scsi-f",
	"internal-50-pin-scsi-m": "internal-50-pin-scsi-m",
	"internal-68-pin-scsi-f": "internal-68-pin-scsi-f",
	"internal-68-pin-scsi-m": "internal-68-pin-scsi-m",
	"modem": "modem",
	"parallel-36-pin": "parallel-36-pin",
	"parallel-f": "parallel-f",
	"parallel-m": "parallel-m",
	"ps-2-f": "ps-2-f",
	"ps-2-m": "ps-2-m",
	"sata-type-a": "sata-type-a",
	"scsi-8mm-68pin": "scsi-8mm-68pin",
	"scsi-micro-d850-m": "scsi-micro-d850-m",
	"scsi-micro-d868-f": "scsi-micro-d868-f",
	"scsi-micro-d868-m": "scsi-micro-d868-m",
	"serial-rs232-f": "serial-rs232-f",
	"serial-rs232-m": "serial-rs232-m",
	"thunderbolt": "thunderbolt"
} as const;
export const portConnectorTypesToImage = {
	"at-keyboard-f": "src/assets/images/enums/portConnectorTypes/at-keyboard-f.png",
	"at-keyboard-m": "src/assets/images/enums/portConnectorTypes/at-keyboard-m.png",
	"e-sata": "src/assets/images/enums/portConnectorTypes/e-sata.png",
	"ethernet": "src/assets/images/enums/portConnectorTypes/ethernet.png",
	"firewire-400": "src/assets/images/enums/portConnectorTypes/firewire-400.png",
	"firewire-800": "src/assets/images/enums/portConnectorTypes/firewire-800.png",
	"firewire": "src/assets/images/enums/portConnectorTypes/firewire.png",
	"gameport": "src/assets/images/enums/portConnectorTypes/gameport.png",
	"ide-40pin-port": "src/assets/images/enums/portConnectorTypes/ide-40pin-port.png",
	"ide-40pin": "src/assets/images/enums/portConnectorTypes/ide-40pin.png",
	"internal-50-pin-scsi-f": "src/assets/images/enums/portConnectorTypes/internal-50-pin-scsi-f.png",
	"internal-50-pin-scsi-m": "src/assets/images/enums/portConnectorTypes/internal-50-pin-scsi-m.png",
	"internal-68-pin-scsi-f": "src/assets/images/enums/portConnectorTypes/internal-68-pin-scsi-f.png",
	"internal-68-pin-scsi-m": "src/assets/images/enums/portConnectorTypes/internal-68-pin-scsi-m.png",
	"modem": "src/assets/images/enums/portConnectorTypes/modem.png",
	"parallel-36-pin": "src/assets/images/enums/portConnectorTypes/parallel-36-pin.png",
	"parallel-f": "src/assets/images/enums/portConnectorTypes/parallel-f.png",
	"parallel-m": "src/assets/images/enums/portConnectorTypes/parallel-m.png",
	"ps-2-f": "src/assets/images/enums/portConnectorTypes/ps-2-f.png",
	"ps-2-m": "src/assets/images/enums/portConnectorTypes/ps-2-m.png",
	"sata-type-a": "src/assets/images/enums/portConnectorTypes/sata-type-a.png",
	"scsi-8mm-68pin": "src/assets/images/enums/portConnectorTypes/scsi-8mm-68pin.png",
	"scsi-micro-d850-m": "src/assets/images/enums/portConnectorTypes/scsi-micro-d850-m.png",
	"scsi-micro-d868-f": "src/assets/images/enums/portConnectorTypes/scsi-micro-d868-f.png",
	"scsi-micro-d868-m": "src/assets/images/enums/portConnectorTypes/scsi-micro-d868-m.png",
	"serial-rs232-f": "src/assets/images/enums/portConnectorTypes/serial-rs232-f.png",
	"serial-rs232-m": "src/assets/images/enums/portConnectorTypes/serial-rs232-m.png",
	"thunderbolt": "src/assets/images/enums/portConnectorTypes/thunderbolt.png"
} as const;
export const PortConnectorTypes = z.nativeEnum(portConnectorTypes);
export type PortConnectorTypes = z.infer<typeof PortConnectorTypes>;