import { z } from "zod";
export const propertyNames = {
	"Album": "album",
	"Assistant": "assistant",
	"Award Categories": "awardCategories",
	"Backline Type": "backlineType",
	"Battery Capacity": "batteryCapacity",
	"Battery Types": "batteryTypes",
	"Blurb": "blurb",
	"Book": "book",
	"Book Genre": "bookGenre",
	"Book Type": "bookType",
	"Brand": "brand",
	"Bra Type": "braType",
	"Bust Size": "bustSize",
	"Capacity": "capacity",
	"Cell Carrier": "cellCarrier",
	"Cell Phone Form Factor": "cellPhoneFormFactor",
	"Chest Size": "chestSize",
	"Circa": "circa",
	"Closure Type": "closureType",
	"Clothing Care": "clothingCare",
	"Club Type": "clubType",
	"Collar Type": "collarType",
	"College": "college",
	"Colors": "colors",
	"Connectivity": "connectivity",
	"Console Type": "consoleType",
	"Copyright": "copyright",
	"Cord Length": "cordLength",
	"Cuff Type": "cuffType",
	"Cut No": "cutNo",
	"Data Transfer Rate": "dataTransferRate",
	"Decade": "decade",
	"Description": "description",
	"Drive Form Factor": "driveFormFactor",
	"Drive Interface": "driveInterface",
	"Drive Type": "driveType",
	"Edition": "edition",
	"Esrb Rating": "esrbRating",
	"Ethnicity": "ethnicity",
	"Features": "features",
	"Fit Type": "fitType",
	"Flex Type": "flexType",
	"Garment Length Type": "garmentLengthType",
	"Gender": "gender",
	"Generation": "generation",
	"Head Size": "headSize",
	"Heel Height": "heelHeight",
	"Height": "height",
	"Height Map Type": "heightMapType",
	"Holiday": "holiday",
	"Includes": "includes",
	"Inseam Size": "inseamSize",
	"Iron Type": "ironType",
	"Jeans Type": "jeansType",
	"Landmark": "landmark",
	"Language": "language",
	"Lapel Type": "lapelType",
	"Leg Style": "legStyle",
	"Length": "length",
	"Length Size": "lengthSize",
	"Lifestyle Type": "lifestyleType",
	"Made Of": "madeOf",
	"Material Style": "materialStyle",
	"Model Name": "modelName",
	"Model No": "modelNo",
	"Movie": "movie",
	"Movie Genre": "movieGenre",
	"Movie Rating": "movieRating",
	"Music Format Type": "musicFormatType",
	"Neck Size": "neckSize",
	"Neck Type": "neckType",
	"Notes": "notes",
	"Occasion Type": "occasionType",
	"Operating System": "operatingSystem",
	"Operating System Name": "operatingSystemName",
	"Operating System Version": "operatingSystemVersion",
	"Origin": "origin",
	"Pages": "pages",
	"Part Numbers": "partNumbers",
	"Person": "person",
	"Pocket Type": "pocketType",
	"Power Type": "powerType",
	"Product Line": "productLine",
	"Pro Sports Team": "proSportsTeam",
	"Province": "province",
	"Read Speed": "readSpeed",
	"Rise Type": "riseType",
	"Rn": "rn",
	"Runtime": "runtime",
	"Shaft Type": "shaftType",
	"Shoe Heel Type": "shoeHeelType",
	"Shoe Width": "shoeWidth",
	"Size": "size",
	"Skirt Type": "skirtType",
	"Sleeve Length": "sleeveLength",
	"Sleeve Size": "sleeveSize",
	"Sleeve Type": "sleeveType",
	"Sports League": "sportsLeague",
	"Sports Type": "sportsType",
	"Strap Type": "strapType",
	"Style No": "styleNo",
	"Suggested Retail Price": "suggestedRetailPrice",
	"Swimsuit Bottom Style": "swimsuitBottomStyle",
	"Swimsuit Top Style": "swimsuitTopStyle",
	"Tested On": "testedOn",
	"Toe Style": "toeStyle",
	"Tv Series": "tvSeries",
	"Tv Series Rating": "tvSeriesRating",
	"Upcs": "upcs",
	"Video Format Type": "videoFormatType",
	"Video Game": "videoGame",
	"Waist Size": "waistSize",
	"Wedge Type": "wedgeType",
	"Weight": "weight",
	"Width": "width",
	"Write Speed": "writeSpeed"
} as const;
export const PropertyNames = z.nativeEnum(propertyNames);
export type PropertyNames = z.infer<typeof PropertyNames>;